version: "3.1"
services:
    redis:
        image: redis
        ports:
            - "6380:6379"
    mariadb:
        image: mariadb
        restart: always
        ports:
            - "5555:3306"
        environment:
            MARIADB_DATABASE: concord
            MARIADB_ROOT_PASSWORD: password
        volumes:
            - ./database/docker-init:/docker-entrypoint-initdb.d
    concord-api:
        build: .
        user: "node"
        container_name: "concord-api"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        depends_on:
            - mariadb
            - redis
        environment:
            WAIT_HOSTS: redis:6379, mariadb:3306
        ports:
            - "7890:7890"
